name: Weekly Updates (Per-Type)

on:
  schedule:
    # Runs Mondays ~07:15 Europe/Brussels (cron is UTC; summer time +2)
    - cron: '15 5 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  models: read

jobs:
  build-weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Rate Limits
        run: |
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /rate_limit
        env:
          GITHUB_TOKEN: ${{ secrets.WEEKLY }}
      - name: Run tracker
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.WEEKLY }}
        run: |
          pwsh ./.github/scripts/updates-weekly.ps1 -RepoRoot . -ContentDir 'content/updates' -MaxAzure 20 -MaxGitHub 12 -MaxTerraform 8 -SkipOnFirstRateLimit $true

      - name: Commit & push (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes"
            exit 0
          fi
          git commit -m "chore(updates): weekly per-type posts"
          git push